apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pyramid.fullname" . }}
  labels:
    {{- include "pyramid.labels" . | nindent 4 }}
data:
  APP_URL: {{ .Values.config.appUrl | quote }}
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  SMTP_HOST: {{ .Values.config.smtpHost | quote }}
  SMTP_PORT: {{ .Values.config.smtpPort | quote }}
  SMTP_FROM: {{ .Values.config.smtpFrom | quote }}
