{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pyramid.fullname" . }}
  labels:
    {{- include "pyramid.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ required "secret.databaseUrl is required when secret.create is true" .Values.secret.databaseUrl | quote }}
{{- end }}
